### ISSUE TITLE
improve watch feature

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3848]
#### To-do list

- [x] bad abstraction in kv layer, add watch ID to identify multiple watches in one watch channel: #3842 

problem: One watcher includes multiple watches, and their events are sent out through one channel. For the received event, user would like to know which watch it belongs to.

<hr>

- [x] the way to return watched events in one txn: https://github.com/coreos/etcd/pull/4091

problem: the changes in one txn should be observed by users at the same time, or users may get half-state.

<hr>

- [x] remove ongoing transaction: https://github.com/coreos/etcd/pull/3817

<hr>

- [x] one watch ID for multiple events: https://github.com/coreos/etcd/pull/4122, https://github.com/coreos/etcd/pull/4120

<hr>

- [ ] inefficiency of event distribution through watch

problem: when reading value and sending out event through gRPC, we now unmarshal it first, then marshal it to byte slice again to distribute each time. This is inefficient.

<hr>

- [ ] add progress notification on watch

problem: user wants to know whether the watch is still working and how far it has gone.

**Comment by yichengq** [comment]
The first points have discussed with xiang. The fifth point was mentioned before, and i also list it here. let me know if you have any thoughts or want to reorganize the list.

**Comment by xiang90** [comment]
> One watcher includes multiple watches, and their events are sent out through one channel. For the received event, user would like to know which watch it belongs to.

The internal go chan is not the real issue. The real issue is for server-client interaction. The client uses one stream per watcher, which means one stream per multiple watches. The client needs to have a way to figure out which watch the received event belong to.

> My thought is to ensure that the events in one txn are returned to users in event slice in one gRPC 

I think we can try batched events in one watch response first.

Another thing we need to add is cancellation.

**Comment by gyuho** [comment]
In the high level, I agree that there should be one TCP connection shared
by X number of clients, as we watch using gRPC. Then it seems like it would be
done in client side, which is currently `etcdctlv3`.

Wrapping 10s of `watch` commands in one TCP connection would be simple but
I am not sure what would be the best way to support this in command line interface.

Any suggestions? @xiang90

**Comment by gyuho** [comment]
I misunderstood. gRPC part is already implemented. I will change the logic to get range histories first.
And will keep track of progress here.

**Comment by gyuho** [comment]
I am working on `add progress notification on watch`. I think good starting point is to figure out
how to fill in the `etcdserverpb.WatchResponse.ResponseHeader` with cluster, member information:

```go
// might add some members here
type watchServer struct {
	watchable storage.Watchable
}
```

https://github.com/coreos/etcd/blob/master/etcdserver/api/v3rpc/watch.go

**Comment by gyuho** [comment]
@xiang90 This feels out of date. Should we close this?

**Comment by xiang90** [comment]
@gyuho Actually we have not finished the last two.

**Comment by gyuho** [comment]
Ok got it. thanks.
