### ISSUE TITLE
*: use Go 1.9+

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#6174]
- [x] Replace import paths of `golang.org/x/net/context` with `context` within etcd (done via https://github.com/coreos/etcd/pull/8511)
- [x] Coordinate with external projects that imports etcd packages with `context` packages
  - [x] discovery, client, clientv3, raft
  - [x] Communicate with Kubernetes (done via https://groups.google.com/d/msg/kubernetes-dev/_YcpsDSSOW0/Aifxsub-CQAJ)
  - [x] Communicate with CockroachDB (done via https://github.com/cockroachdb/cockroach/issues/18348)
  - [x] Communicate with dgraph (done via https://github.com/dgraph-io/dgraph/issues/1423)
  - [x] Communicate with chain (done via https://github.com/chain/chain/issues/1466)
- [x] Request to replace `golang.org/x/net/context` with `context` in upstream dependencies
  - [x] google.golang.org/grpc (https://github.com/grpc/grpc-go/pull/1160)
  - [ ] github.com/golang/protobuf (TODO https://github.com/golang/protobuf/issues/336)
  - [ ] github.com/gogo/protobuf (TODO https://github.com/gogo/protobuf/issues/282)
  - [ ] github.com/grpc-ecosystem/grpc-gateway (TODO https://github.com/grpc-ecosystem/grpc-gateway/pull/343)
  - [x] golang.org/x/time https://github.com/golang/go/issues/16745 (done via https://github.com/golang/time/commit/c06e80d9300e4443158a03817b8a8cb37d230320)
  - [x]  golang.org/x/net/trace (done via https://github.com/golang/net/commit/c8c74377599bd978aee1cf3b9b63a8634051cec2)
- [x] fix all other issues with `staticcheck` (done via https://github.com/coreos/etcd/pull/7602)
- [x] `io.Seek*` https://github.com/coreos/etcd/pull/6296
- [x] use `time.Until` (done via https://github.com/coreos/etcd/pull/7737)
- [x] `tls.Config` copy method https://golang.org/pkg/crypto/tls/#Config.Clone to replace `ShallowCopyTLSConfig` at https://github.com/coreos/etcd/blob/master/pkg/transport/listener.go (done via https://github.com/coreos/etcd/pull/7737)
- [x] add `mutex` profile handler to `embed/serve.go` https://golang.org/pkg/runtime/pprof/#Profile (done via https://github.com/coreos/etcd/pull/7765)
- [x] `*url.URL.Hostname()`, `*url.URL.Port()` https://golang.org/doc/go1.8#net_url (done via https://github.com/coreos/etcd/pull/7766)
- [x] Graceful shutdown gRPC server; see https://github.com/coreos/etcd/issues/7322#issuecomment-287154235 (done via https://github.com/coreos/etcd/pull/7743)
- [x] `CloseNotify` in `ServeHTTP` https://github.com/golang/go/issues/9524#issuecomment-271937649 (not needed for etcd use case?)
- [x] `http.Server.Shutdown` https://golang.org/doc/go1.8#http_shutdown (done via https://github.com/coreos/etcd/pull/7879)
- [ ] Use [`net.DialContext`](https://github.com/golang/go/blob/master/src/net/dial.go#L295), [`http.Transport.DialContext`](https://github.com/golang/go/blob/master/src/net/http/transport.go#L90-L100) in `pkg/transport` (TODO: done via https://github.com/coreos/etcd/pull/7602)
- [ ] Use [`http.Request.WithContext`](https://github.com/golang/go/blob/master/src/net/http/request.go#L288-L290) for `httputil.RequestCanceler`
- [x] Use monotime (done via https://github.com/coreos/etcd/pull/8507)

**Comment by xiang90** [comment]
move to 3.2. we will release 3.2 with go 1.8.

**Comment by c4pt0r** [comment]
btw, tidb imports etcd packages too :)

**Comment by lukaszo** [comment]
This hack https://github.com/coreos/etcd/blob/master/pkg/transport/transport.go#L66-L71 doesn't work in 1.8 anymore :(

**Comment by gyuho** [comment]
Moving to 3.3. Hopefully, Go 1.9 addresses https://github.com/golang/protobuf/issues/336.

**Comment by gyuho** [comment]
Closing and opening a new issue on contexts in generated code.
