### ISSUE TITLE
Clarify/define clientv3 retry logic (fix broken retries)

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8691]
Now that retry logic is such a critical part of our balancer logic, we need document clearly when Go client retries its RPCs; currently we don't have any, other than some comments in `clientv3/retry.go`. Should be helpful for other client language bindings.

### release-3.2, as of [f1d7dd8](https://github.com/coreos/etcd/blob/f1d7dd87da3e8feab4aaf675b8e29c6a5ed5f58b/clientv3/retry.go)

Mutable/immutable RPCs share the same error handling logic:

1. no error is returned, then no retry
2. if the error is [`rpctypes.EtcdError`](https://github.com/coreos/etcd/blob/master/etcdserver/api/v3rpc/rpctypes/error.go) type, then no retry
   - e.g. `rpctypes.ErrEmptyKey`, `rpctypes.ErrNoSpace`, `rpctypes. ErrTimeout`
3. if the error is [`grpc/status.(*statusError)`](https://github.com/grpc/grpc-go/blob/master/status/status.go) type and its error code is `codes.Unavailable` which means the service is not currently available, then retry

`rpctypes.EtcdError` and `grpc/status.(*statusError)` errors are mutually exclusive.
This only works with `grpc/grpc-go` v1.2.1. 

### master branch, as of [764a0f7](https://github.com/coreos/etcd/blob/764a0f79b2dc4d815b6f0ed868bbd4b8af52610a/clientv3/retry.go)

`grpc/grpc-go` upgraded to >v1.6.x, which changed the behavior of error handling.

During network disconnections, error [`clientv3.ErrNoAddrAvilable`](https://github.com/coreos/etcd/blob/master/clientv3/balancer.go#L30) can happen, and its error code is `codes.Unavailable`, so should be retried (same as `grpc.Errorf(codes.Unavailable, "there is no address available")`).

However, due to the [change in grpc-go](https://github.com/grpc/grpc-go/pull/1369), [`transport.ErrStreamDrain`](https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L691) can be returned. etcd mutable RPCs should not be retried on `transport.ErrStreamDrain` and only retried on [`clientv3.ErrNoAddrAvilable`](https://github.com/coreos/etcd/blob/master/clientv3/balancer.go#L30). This is fixed via https://github.com/coreos/etcd/pull/8335 (fix "put at most once", not in 3.2).

Plus with health checking balancer https://github.com/coreos/etcd/pull/8545, now retry error handling logic is:

1. no error is returned, then no retry (no matter what RPCs are)
2. for immutable requests, if the error is `grpc/status.(*statusError)` type and its error code is `codes.Unavailable`, then mark unhealthy, endpoint-switch, wait for connection notify, and retry
3. for mutable requests, if the error is `grpc/status.(*statusError)` type and its error code is `codes.Unavailable` and the error message is `there is no address available`, then mark unhealthy, endpoint-switch, wait for connection notify, and retry
4. for immutable requests, if the error is `rpctypes.EtcdError` type, then mark unhealthy, endpoint-switch, and exit
   - e.g. `rpctypes.ErrEmptyKey`, `rpctypes.ErrNoSpace`, `rpctypes. ErrTimeout`
5. for mutable requests, if the error is `rpctypes.EtcdError` type, then mark unhealthy, endpoint-switch, and exit (proper handling is missing though)

### TODOs

- [X] handle stale endpoints health status (done via https://github.com/coreos/etcd/pull/8714)
- [X] distinguish mutable/immutable RPCs in `Maintenance` API, and others (done via https://github.com/coreos/etcd/pull/8717)
- [ ] clean up retry wrapper (done via https://github.com/coreos/etcd/pull/8724)
- [ ] do auth wrapper consistent in all RPCs (done via https://github.com/coreos/etcd/pull/8724)
- [ ] handle `status.FromError` https://github.com/grpc/grpc-go/issues/1581
- [ ] `rpctypes.EtcdError` type error handling should be consistent across mutable/immutable RPCs
- [ ] make retrial logic consistent with our [`functional-tester/stresser`](https://github.com/coreos/etcd/blob/master/tools/functional-tester/etcd-tester/key_stresser.go#L90-L141)
- [ ] do not mark as unhealthy on `rpctypes.ErrEmptyKey` or `rpctypes.ErrNoSpace`
    - only does on `rpctypes.ErrTimeout`
- [ ] do not trigger endpoint switch on `rpctypes.ErrEmptyKey` or `rpctypes.ErrNoSpace`
    - only does on `rpctypes.ErrTimeout`
- [ ] consolidate retry logic across clientv3 (e.g. clientv3/leasing acquire has its own retrial logic)

**Comment by xiang90** [comment]
is this fixed?

**Comment by gyuho** [comment]
Yes.

**Comment by devnev** [comment]
Hi. The Watch client still contains a failFast=False with a TODO to switch it to failFast=True. Was that meant to be part of this issue? Or is there an issue tracking that elsewhere?

**Comment by gyuho** [comment]
@devnev We've disabled `FailFast=true` to all RPCs, replaced by internal, manual retry in clientv3 side. 

We've covered some network fault cases in https://github.com/coreos/etcd/issues/8711, if that helps.

For watch, clientv3 (>=v3.2.10) should be able to switch and retry when a server fails.

**Comment by devnev** [comment]
> We've disabled FailFast=true to all RPCs

@gyuho thas is incorrect, see https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L778

**Comment by devnev** [comment]
A [search of the codebase](https://sourcegraph.com/search?q=FailFast+-file:.*/vendor/.*+-file:.*test.*&sq=repo:%5Egithub%5C.com/coreos/etcd%24) also reveals a FailFast=false in the grpcproxy

**Comment by gyuho** [comment]
@devnev Indeed.

I meant to say

> We've disabled FailFast=false

Somehow got confused.

So we do `FailFast=false` for watch, but for others `FailFast=true`, thus gRPC side retry is disabled. But note that that watch has for-loop for manual retry, since we assume gRPC retry logic is not stable enough.

**Comment by devnev** [comment]
For watches in particular FailFast=False is problematic, as they usually do not have RPC timeouts. In our case the connections are failing for extended periods of times, but we cannot set a timeout on the request as it is a watch. However, because FailFast=False, we're also not given any indication that the watch is in fact broken.

**Comment by gyuho** [comment]
etcd watch API is not meant for detecting connection issues. Disconnect is handled in client balancer layer. We've added [HTTP/2 keepalive](https://godoc.org/github.com/coreos/etcd/clientv3#Config) and client balancer health checking (only available >= v3.2.10).

Please try HTTP/2 keepalive ping. If it still doesn't work, file open a new issue.
