### ISSUE TITLE
Documentation: explain TLS changes

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8798]
A few breaking changes happened in TLS authentication in 3.2 and upcoming 3.3 release.
Need clarify/update security docs, upgrade guide, or FAQ.

3.2:
- [ ] [#7687](https://github.com/coreos/etcd/pull/7687) transport: deny incoming peer certs with wrong IP SAN
- [ ] [#7767](https://github.com/coreos/etcd/pull/7767) transport: resolve DNSNames when SAN checking
- [ ] [#7829](https://github.com/coreos/etcd/pull/7829) pkg/transport: reload TLS certificates for every client requests
- [ ] https://github.com/coreos/etcd/pull/8651#issuecomment-342979191

3.3:
- [ ] https://github.com/coreos/etcd/issues/8206
- [ ] https://github.com/coreos/etcd/issues/8268
- [x] https://github.com/coreos/etcd/issues/8445
- [ ] https://github.com/coreos/etcd/issues/8534
- [ ] https://github.com/coreos/etcd/issues/8578
- [ ] https://github.com/coreos/etcd/issues/8600
- [ ] https://github.com/coreos/etcd/issues/8603
- [ ] https://github.com/coreos/etcd/issues/8797
- [ ] https://github.com/coreos/etcd/issues/8803
- [x] https://github.com/coreos/etcd/pull/8651#issuecomment-342979191
